#parameter value
which_visits: [0]  #[0,1,2,3,4,5,6]
#norb: 4
#GRISM: G141 #G102
#FILTER: F130N #F139M
#exp_time: 69.617 #138.381
path: /home/zieba/Desktop/Data/L-98-59_Hubble15856 #/home/zieba/Desktop/Data/GJ1214_Hubble13021 # #/home/zieba/Desktop/Data/WASP33_Hubble15109
#nexp: 302
toffset: 2458366
###
direct_image_diagnostics: True # show direct image
direct_image_output: True # save direct image and xrefyref
di_rmin: 270 #130 #270 #130 #
di_rmax: 290 #160 #285 #155 #
di_cmin: 245 #15 #245 #125 #
di_cmax: 265 #35 #260 #150 #
###
trace_image_output: True  # save trace
trace_image_show: False  # show trace
all_image_output: True # save all pics
all_image_show: False  # show all pics
sig_cut: 15
nsmooth: 9
diagnostics: False
output: True
opt_extract: True
correct_wave_shift: True
plot_trace: True
plot_spectrum: False
one_di_per_visit: False
rmin: 0
rmax: 512 #255 #512
cmin: 0
cmax: 512 #255 #512
skyrmin: 15
skyrmax: 70
skycmin: 20 #100 #400
skycmax: 100 #200 #500
offset: 0 #int
rdnoise: 22.0
window: 150
###				
BEAMA_i: 15 #41
BEAMA_f: 196 #248
flat: ancil/flats/WFC3.IR.G141.flat.2.fits #ancil/flats/WFC3.IR.G102.flat.2.fits
###		
lc_type: transit
skip_orbs_phase_curve: 0_
skip_orbs_eclipse: 0_
skip_orbs_transit: 0_7_
###
ld_file: /ancil/LD_coefficients/HIP41378_ld_coeffs.dat
fix_ld: False
###
### Wavelength bins
#wave_bins = np.linspace(1.125, 1.65, 22)*1e4
#wave_bins = np.linspace(1.125, 1.65, 12)*1e4
#wave_bins = np.linspace(1.139, 1.631, 12)*1e4
#wave_bins = np.array([11400, 11800, 12200,12600,13000, 13400, 13800, 14200, 14600, 15000, 15400, 15800, 16200])
wvl_min: 1.125
wvl_max: 1.65
wvl_bins: [12, 24]
###
Teff: 3412
logg: 4.94 
MH: -0.5
sm: phoenix #kurutz #
###
background_box: False
background_thld: 1000
