#parameter value
nvisit: 1
norb: 5
GRISM: G102
FILTER: F139M
exp_time: 138.381
path: /home/zieba/Desktop/Data/WASP33_Hubble15109
nexp: 302
toffset: 245500.
###
direct_image_diagnostics: True
direct_image_output: True
di_rmin: 270 #130 #
di_rmax: 285 #155 #
di_cmin: 245 #125 #
di_cmax: 260 #150 #
###			
sig_cut: 15
nsmooth: 9
diagnostics: False
output: True
opt_extract: True
correct_wave_shift: True
plot_trace: True
plot_spectrum: False
one_di_per_visit: False
rmin: 0
rmax: 512
cmin: 0
cmax: 512
skyrmin: 10
skyrmax: 70
skycmin: 400
skycmax: 500
offset: 0 #int
rdnoise: 22.0
window: 150
###				
BEAMA_i: 41
BEAMA_f: 248
flat: config/WFC3.IR.G102.flat.2.fits
###		
lc_type: transit
skip_orbs_phase_curve: 0_
skip_orbs_eclipse: 0_
skip_orbs_transit: 0_7_
###
ld_file: LD_coefficients/HIP41378_ld_coeffs.dat
fix_ld: False
